### ISSUE TITLE
add DateWidget

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-administration#149]
<img width="1156" alt="Screenshot 2022-12-05 at 11 03 44" src="https://user-images.githubusercontent.com/38131488/205609697-a08b34d6-7328-4b3a-b1ca-10b61277e220.png">

We need a date widget to be added for DateField, like the one represented on the screenshot.
Existing widgets are already available in the react-invenio-forms. The new widget component **must** follow the same interface structure as the existing ones - so that it can be also reused in the future - some of the modules are expecting the same props in all the defined widgets.

When the widget is defined properly it only needs to be added to the invenio-administration component mapping, instead of `Input`: 
https://github.com/inveniosoftware/invenio-administration/blob/main/invenio_administration/assets/semantic-ui/js/invenio_administration/src/formik/GenerateForm.js#L14

- [ ] in addition: fix the field label to remove `_` and the styling of action buttons area inside the modal (ask @kpsherva how to fix it quickly)

**Comment by jennur** [comment]
## Postponed as it needs more investigation. 

I've tried to use the the same module ([`semantic-ui-calendar-react`](https://github.com/arfedulov/semantic-ui-calendar-react)) used in [`ils`](https://github.com/inveniosoftware/react-invenio-app-ils/blob/f5063e405ecab33c1ee7d1dcd8d9df17fe89e24c/src/lib/components/DatePicker/DatePicker.js), but it seems to not be working in `react-invenio-forms`. 

I'm getting some weird errors in the imported component that I've not been able to solve:

![Image](https://user-images.githubusercontent.com/21052053/212714139-734e4c46-dc07-4951-8ca2-4d95316533a8.png)
Everything looks fine in the `<InputView/>` component, so maybe it's not compatible (the latest commit in this module was in 2019, so it doesn't seem to be maintained).


### Possible other modules we can use

- [react-semantic-ui-datepickers](https://www.npmjs.com/package/react-semantic-ui-datepickers)
    - Has semantic ui theming out of the box
- [react-dates](https://www.npmjs.com/package/react-dates)
    - The AirBnb date picker, also used in [indico](https://indico.cern.ch/rooms/book), see code [here](https://github.com/indico/newdle/blob/7e9c1ca0375a72a9f83c425dc76ed42e6ea31b57/newdle/client/src/components/common/Calendar.js).
    - See the Storybook [here](http://react-dates.github.io/react-dates/?path=/story/daterangepicker-drp--default)
    - Does not have semantic-ui styling, but maybe it can be overridden somehow?
