### ISSUE TITLE
features communities saves but does not feature

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-administration#169]
After saving the feature community on the administration UI, it does not appear in the frontpage. Meaning it is actually not features.
However, it does seem to be stored somewhere:

![image](https://user-images.githubusercontent.com/6756943/235093636-37362aae-30fd-456a-81c1-cd946063a31c.png)

Karolina mentioned that there might be hardcoded ids somewhere.

Momentarily I featured them via REST API.

**Comment by kpsherva** [comment]
tested, it works properly
